-- ==============================================================================
-- SchedX — Smart Timetable Generator
-- Supabase PostgreSQL Schema
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Project Dashboard (https://supabase.com/dashboard)
-- 2. Navigate to: SQL Editor -> New query
-- 3. Paste this entire file and click "Run"
-- ==============================================================================

-- Enable pgcrypto extension for utility functions if needed
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 1. TEACHERS TABLE
-- Stores faculty/instructor profiles
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.teachers (
  teacher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_name TEXT NOT NULL,
  specialization TEXT,
  working_days_per_week INTEGER DEFAULT 5 CHECK (working_days_per_week BETWEEN 1 AND 7),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 2. COURSES / SUBJECTS TABLE
-- Stores academic courses/subjects offered
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.courses (
  course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 3. TEACHER_COURSES TABLE
-- Represents which teacher can teach which course (many-to-many relationship)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.teacher_courses (
  teacher_id BIGINT REFERENCES public.teachers(teacher_id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES public.courses(course_id) ON DELETE CASCADE,
  PRIMARY KEY (teacher_id, course_id)
);

-- ==============================================================================
-- 4. CLASSES TABLE
-- Stores student cohort / batch / section data
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.classes (
  class_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name TEXT NOT NULL,
  section TEXT DEFAULT 'A',
  student_count INTEGER NOT NULL CHECK (student_count > 0),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT uq_class_section UNIQUE (class_name, section)
);

-- ==============================================================================
-- 5. ROOMS TABLE
-- Stores classrooms and laboratories with strict room_type validation
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.rooms (
  room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_name TEXT NOT NULL UNIQUE,
  room_type TEXT NOT NULL CHECK (room_type IN ('Classroom', 'Laboratory')),
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 6. TIME_SLOTS TABLE
-- Represents schedule periods across days of the week (1 = Monday ... 7 = Sunday)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.time_slots (
  slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  is_break BOOLEAN DEFAULT FALSE,
  CONSTRAINT uq_day_time_slot UNIQUE (day_of_week, start_time, end_time)
);

-- ==============================================================================
-- 7. TEACHER_AVAILABILITY TABLE
-- Stores explicit teacher availability for specific time slots
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.teacher_availability (
  availability_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT REFERENCES public.teachers(teacher_id) ON DELETE CASCADE,
  slot_id BIGINT REFERENCES public.time_slots(slot_id) ON DELETE CASCADE,
  is_available BOOLEAN DEFAULT TRUE,
  CONSTRAINT uq_teacher_slot UNIQUE (teacher_id, slot_id)
);

-- ==============================================================================
-- 8. TIMETABLE TABLE
-- The generated conflict-free schedule entries
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.timetable (
  timetable_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_id BIGINT REFERENCES public.time_slots(slot_id) ON DELETE CASCADE,
  teacher_id BIGINT REFERENCES public.teachers(teacher_id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES public.courses(course_id) ON DELETE CASCADE,
  class_id BIGINT REFERENCES public.classes(class_id) ON DELETE CASCADE,
  room_id BIGINT REFERENCES public.rooms(room_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Conflict prevention constraints:
  -- 1. Same teacher cannot teach two classes at the same time
  CONSTRAINT uq_slot_teacher UNIQUE (slot_id, teacher_id),
  -- 2. Same class cannot be in two rooms/subjects at the same time
  CONSTRAINT uq_slot_class UNIQUE (slot_id, class_id),
  -- 3. Same room cannot be assigned to two classes at the same time
  CONSTRAINT uq_slot_room UNIQUE (slot_id, room_id)
);

-- ==============================================================================
-- INDEXES FOR HIGH PERFORMANCE QUERIES
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_timetable_slot ON public.timetable(slot_id);
CREATE INDEX IF NOT EXISTS idx_timetable_teacher ON public.timetable(teacher_id);
CREATE INDEX IF NOT EXISTS idx_timetable_course ON public.timetable(course_id);
CREATE INDEX IF NOT EXISTS idx_timetable_class ON public.timetable(class_id);
CREATE INDEX IF NOT EXISTS idx_timetable_room ON public.timetable(room_id);
CREATE INDEX IF NOT EXISTS idx_time_slots_day ON public.time_slots(day_of_week);
CREATE INDEX IF NOT EXISTS idx_teacher_avail_teacher ON public.teacher_availability(teacher_id);

-- ==============================================================================
-- SEED DATA: Standard Default Rooms & Time Slots
-- ==============================================================================

-- Seed default classrooms & laboratories
INSERT INTO public.rooms (room_name, room_type, capacity) VALUES
('Classroom-101', 'Classroom', 60),
('Classroom-102', 'Classroom', 70),
('Classroom-103', 'Classroom', 50),
('Lab-201', 'Laboratory', 40),
('Lab-202', 'Laboratory', 45)
ON CONFLICT (room_name) DO NOTHING;

-- Seed default standard 1-hour time slots for Monday (1) through Friday (5)
-- Working hours 09:00 to 16:00
DO $$
DECLARE
  day_num INTEGER;
  slot_start TIME;
  slot_end TIME;
BEGIN
  FOR day_num IN 1..5 LOOP
    -- 09:00 - 10:00
    INSERT INTO public.time_slots (day_of_week, start_time, end_time, is_break)
    VALUES (day_num, '09:00:00', '10:00:00', false)
    ON CONFLICT (day_of_week, start_time, end_time) DO NOTHING;

    -- 10:00 - 11:00
    INSERT INTO public.time_slots (day_of_week, start_time, end_time, is_break)
    VALUES (day_num, '10:00:00', '11:00:00', false)
    ON CONFLICT (day_of_week, start_time, end_time) DO NOTHING;

    -- 11:00 - 12:00
    INSERT INTO public.time_slots (day_of_week, start_time, end_time, is_break)
    VALUES (day_num, '11:00:00', '12:00:00', false)
    ON CONFLICT (day_of_week, start_time, end_time) DO NOTHING;

    -- 12:00 - 13:00 (Lunch Break)
    INSERT INTO public.time_slots (day_of_week, start_time, end_time, is_break)
    VALUES (day_num, '12:00:00', '13:00:00', true)
    ON CONFLICT (day_of_week, start_time, end_time) DO NOTHING;

    -- 13:00 - 14:00
    INSERT INTO public.time_slots (day_of_week, start_time, end_time, is_break)
    VALUES (day_num, '13:00:00', '14:00:00', false)
    ON CONFLICT (day_of_week, start_time, end_time) DO NOTHING;

    -- 14:00 - 15:00
    INSERT INTO public.time_slots (day_of_week, start_time, end_time, is_break)
    VALUES (day_num, '14:00:00', '15:00:00', false)
    ON CONFLICT (day_of_week, start_time, end_time) DO NOTHING;

    -- 15:00 - 16:00
    INSERT INTO public.time_slots (day_of_week, start_time, end_time, is_break)
    VALUES (day_num, '15:00:00', '16:00:00', false)
    ON CONFLICT (day_of_week, start_time, end_time) DO NOTHING;
  END LOOP;
END $$;
