const express=require("express"), cors=require("cors"), mysql=require("mysql2/promise"), path=require("path"), fs=require("fs"), dotenv=require("dotenv");
dotenv.config();
const app=express(); app.use(cors()); app.use(express.json());
const cfg={host:process.env.DB_HOST||"localhost",user:process.env.DB_USER||"root",password:process.env.DB_PASSWORD||"",database:process.env.DB_NAME||"smartschedule",waitForConnections:true,connectionLimit:10};
let pool;
async function db(){if(!pool)pool=mysql.createPool(cfg);return pool;}
async function ensureSchema(){
 const root=await mysql.createConnection({host:cfg.host,user:cfg.user,password:cfg.password});
 await root.query(`CREATE DATABASE IF NOT EXISTS \`${cfg.database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`); await root.end();
 const p=await db(); const sql=fs.readFileSync(path.join(__dirname,"database","smartschedule.sql"),"utf8");
 // SQL file contains CREATE/INSERT statements; execute statement by statement so it also works in mysql2.
 for(const statement of sql.split(/;\s*(?:\r?\n|$)/).map(x=>x.trim()).filter(Boolean)){try{await p.query(statement)}catch(e){if(!/database exists|duplicate/i.test(e.message)) throw e;}}
}
app.get("/api/health",async(req,res)=>{try{const p=await db();await p.query("SELECT 1");res.json({database:true})}catch(e){res.status(503).json({database:false,error:"MySQL is not reachable. Check MySQL service and .env."})}});
const tableMap={courses:"course_id",teachers:"teacher_id",classes:"class_id",rooms:"room_id"};
for(const [table,id] of Object.entries(tableMap)){
 app.get(`/api/${table}`,async(req,res)=>{try{const p=await db();const [rows]=await p.query(`SELECT * FROM ${table} ORDER BY ${id} DESC`);res.json(rows)}catch(e){res.status(500).json({error:"Could not load data. Check MySQL connection."})}});
 app.delete(`/api/${table}/:id`,async(req,res)=>{try{const p=await db();await p.query(`DELETE FROM ${table} WHERE ${id}=?`,[req.params.id]);res.json({message:"Deleted"})}catch(e){res.status(400).json({error:"This record cannot be deleted because it is used by another record."})}});
}
app.post("/api/courses",async(req,res)=>{try{const {name,department,course_type,credits,students,weekly_periods}=req.body;if(!name)return res.status(400).json({error:"Course name is required."});const p=await db();const [r]=await p.query("INSERT INTO courses(name,department,course_type,credits,students,weekly_periods) VALUES(?,?,?,?,?,?)",[name,department||"General",course_type||"Major",credits||3,students||30,weekly_periods||3]);res.json({id:r.insertId})}catch(e){res.status(400).json({error:"Course could not be saved."})}});
app.post("/api/teachers",async(req,res)=>{try{const {name,department,specialization,availability}=req.body;if(!name)return res.status(400).json({error:"Teacher name is required."});const p=await db();const [r]=await p.query("INSERT INTO teachers(name,department,specialization,availability) VALUES(?,?,?,?)",[name,department||"General",specialization||"General",availability||"Mon-Fri"]);res.json({id:r.insertId})}catch(e){res.status(400).json({error:"Teacher could not be saved."})}});
app.post("/api/classes",async(req,res)=>{try{const {name,section,semester,students}=req.body;if(!name)return res.status(400).json({error:"Class name is required."});const p=await db();const [r]=await p.query("INSERT INTO classes(name,section,semester,students) VALUES(?,?,?,?)",[name,section||"A",semester||1,students||30]);res.json({id:r.insertId})}catch(e){res.status(400).json({error:"Class could not be saved."})}});
app.post("/api/rooms",async(req,res)=>{try{const {room_name,room_type,capacity,facilities}=req.body;if(!room_name)return res.status(400).json({error:"Room name is required."});const p=await db();const [r]=await p.query("INSERT INTO rooms(room_name,room_type,capacity,facilities) VALUES(?,?,?,?)",[room_name,room_type||"Classroom",capacity||40,facilities||""]);res.json({id:r.insertId})}catch(e){res.status(400).json({error:"Room could not be saved. Room name may already exist."})}});
app.get("/api/timetable",async(req,res)=>{try{const p=await db();const [rows]=await p.query(`SELECT t.timetable_id,t.day,ts.start_time,ts.end_time,c.name class_name,c.section,co.name course_name,te.name teacher_name,r.room_name FROM timetable t JOIN time_slots ts ON ts.slot_id=t.slot_id JOIN classes c ON c.class_id=t.class_id JOIN courses co ON co.course_id=t.course_id JOIN teachers te ON te.teacher_id=t.teacher_id JOIN rooms r ON r.room_id=t.room_id ORDER BY FIELD(t.day,'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'),ts.start_time,c.name`);res.json(rows)}catch(e){res.status(500).json({error:"Could not load timetable."})}});
app.delete("/api/timetable",async(req,res)=>{try{const p=await db();await p.query("DELETE FROM timetable");res.json({message:"Timetable cleared"})}catch(e){res.status(500).json({error:"Could not clear timetable."})}});
function matchTeacher(course,teachers,used){const exact=course.name.toLowerCase();return teachers.find(t=>!used.has(t.teacher_id)&&((t.specialization||"").toLowerCase().includes(exact)||exact.includes((t.specialization||"").toLowerCase())))||teachers.find(t=>!used.has(t.teacher_id)&&((t.department||"").toLowerCase()===(course.department||"").toLowerCase()))||teachers.find(t=>!used.has(t.teacher_id));}
app.post("/api/generate",async(req,res)=>{try{const p=await db();const [[courses],[teachers],[classes],[rooms],[slots]]=await Promise.all([p.query("SELECT * FROM courses"),p.query("SELECT * FROM teachers"),p.query("SELECT * FROM classes"),p.query("SELECT * FROM rooms"),p.query("SELECT * FROM time_slots ORDER BY start_time")]);if(!courses.length)return res.status(400).json({error:"Add at least one course first."});if(!teachers.length)return res.status(400).json({error:"Add at least one teacher first."});if(!classes.length)return res.status(400).json({error:"Add at least one class first."});if(!rooms.length)return res.status(400).json({error:"Add at least one room first."});
 await p.query("DELETE FROM timetable"); const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; const teacherBusy=new Set(),classBusy=new Set(),roomBusy=new Set(); const jobs=[]; for(const cl of classes)for(const co of courses)for(let i=0;i<Number(co.weekly_periods||1);i++)jobs.push({cl,co}); jobs.sort((a,b)=>(b.co.weekly_periods||1)-(a.co.weekly_periods||1)); const rows=[];
 for(const job of jobs){let ok=false; for(const day of days){if(ok)break;for(const slot of slots){if(ok)break;const ck=`${job.cl.class_id}|${day}|${slot.slot_id}`;if(classBusy.has(ck))continue;for(const room of rooms){if(room.capacity<job.cl.students||((job.co.course_type==="Lab")&&!/lab/i.test(room.room_type)))continue;const rk=`${room.room_id}|${day}|${slot.slot_id}`;if(roomBusy.has(rk))continue;const teacher=matchTeacher(job.co,teachers,teacherBusy);if(!teacher)continue;const tk=`${teacher.teacher_id}|${day}|${slot.slot_id}`;if(teacherBusy.has(tk))continue;rows.push([day,slot.slot_id,job.cl.class_id,job.co.course_id,teacher.teacher_id,room.room_id]);teacherBusy.add(tk);classBusy.add(ck);roomBusy.add(rk);ok=true;break;}}} if(!ok)return res.status(400).json({error:`Could not place ${job.co.name} for ${job.cl.name} ${job.cl.section}. Add more teachers/rooms/time slots or reduce periods per week.`});}
 await p.query("INSERT INTO timetable(day,slot_id,class_id,course_id,teacher_id,room_id) VALUES ?",[rows]);res.json({generated:rows.length,message:"Timetable generated successfully"});
}catch(e){console.error(e);res.status(500).json({error:"Timetable generation failed. Please check your input data."})}});
app.use(express.static(path.join(__dirname,"public"))); app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
const port=Number(process.env.PORT||3000); ensureSchema().then(()=>app.listen(port,()=>console.log(`SmartSchedule running at http://localhost:${port}`))).catch(e=>{console.error("Startup failed:",e.message);process.exit(1)});
